### ISSUE TITLE
[Bug]: i can click the rectangles

### ISSUE THREAD

**Issue by NickBurnett** [UTDNebula/utd-trends#113]
### What did you expect to happen?

i did not expect it to select

### What happened?

it was selected and the color changed to a not nice color

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
you guys need better debug messages
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
@NickBurnett Can you please provide a screenshot of the issue to make it more clear what this is referring to?

**Comment by AbhiramTadepalli** [comment]
![image](https://github.com/user-attachments/assets/a5d8b37f-61cb-4d9d-9d12-2751b5007055)
This is reproduceable: just click on a bar in any bar graph and move the cursor away. The color on the selected bar is darker (in light mode at least) and stays that way until you click on the bar again.

**Comment by AbhiramTadepalli** [comment]
took long enough 😉
