### ISSUE TITLE
[Bug]: Spelling error on hover text

### ISSUE THREAD

**Issue by dlaunikitis** [UTDNebula/utd-trends#114]
### What did you expect to happen?

I just wanted to throw an issue in about some hover text I saw. When hovering the question mark next to average GPA on the grade graph screen "average" is misspelled. The project is looking great :)

### What happened?

^^

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment]
@George-Zhang5246  Is your branch tracking this change?
