### ISSUE TITLE
[Feature Request] Dataset component (Experience tab)

### ISSUE THREAD

**Issue by iamwood** [UTDNebula/utd-trends#147]
# Overview

This part of the dataset component should give the users a clear overview of the specific dataset's course evaluations. Currently, the scraping for this is still in progress, so the exact information to be displayed has not be determined yet. Providing placeholder spots for data should be enough to modify later to complete this feature. 

# Proposal

Implement the design shown in the main card on `Search Page (by class)`.

## Supplementary Information

The design can be viewed in the main card on `Search Page (by class)` in the Figma, as well as labeled `extended-view-experience` in the Components page

**Comment by TyHil** [comment]
@AbhiramTadepalli should this be closed since course evaluation data is no longer on the horizon?

**Comment by AbhiramTadepalli** [comment]
mhm

**Comment by AbhiramTadepalli** [comment]
Yes
