### ISSUE TITLE
[Feature Request] Dropdowns for searching

### ISSUE THREAD

**Issue by iamwood** [UTDNebula/utd-trends#149]
# Overview

This part of the main navigation bar should provide users with a clear way of selecting options from a multi-tiered set of options. Our dataset(s) can be split and or grouped according to multiple intersecting categories (most notably professors and courses), so ideally these menus would be dynamically rendered according to an easily modified tiered registry.

# Proposal

The final design of this has not been established, so a working prototype of this sort of multi-tiered option selection should be a good starting place to generate ideas from.

## Supplementary Information

This feature has not been entirely built-out yet, so if you are interested in working on it, please reach out in the Discord and or make a comment here in this Issue.

**Comment by Jake3231** [comment]
Is this partly addressed by #138? Or related in terms of timeline?
