### ISSUE TITLE
[Feature Request] Add local storage for Dashboard

### ISSUE THREAD

**Issue by eboysen** [UTDNebula/utd-trends#16]
# Overview

Describe the motivation behind your desired functionality.
This functionality is designed to allow for users to reload the page and navigate between pages without losing their search history.

How would you like the user experience for this feature to work?
The 3 search terms and their related json data should be saved in the browser cache local storage so that the user does not have to re-enter their search terms on page reload and queries do not have to be resubmitted to the API.

# Proposal

Describe what changes need to be implemented to resolve this issue. Be as
detailed as possible so maintainers can best determine how to implement this
new feature.
The dashboard page should be set a local storage variable whenever the state of the search data is updated. Making use of the localStorage web object. This can likely be implemented by making use of the useEffect hooks in the page component with a dependency of the search state.

## Supplementary Information

To give your feature more chance at being implemented, feel free to attach any
other documentation. For something highly-user facing, a UI mock-up or some
other form of wireframe is required.

**Comment by Spaceface16518** [comment]
The [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) might be worth considering for this. It uses service workers and has pretty good [cross-browser support](https://caniuse.com/mdn-api_cache).

**Comment by TyHil** [comment]
Resolved with pull request #64
