### ISSUE TITLE
Uniform Skeleton for Course and Professor Overview components

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#171]
### What did you expect to happen?

When loading, since the course number / professor name is already known, it does not "load" in the RHS components.

### What happened?

For visual consistency, the course number / professor's loading should be chained to a different ~component~ piece of data that actually loads

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiramTadepalli** [comment]
@TyHil Is this a valid request?

**Comment by AbhiramTadepalli** [comment]
How do we handle if the rest of the component doesn't load?

**Comment by TyHil** [comment]
@AbhiramTadepalli what does "chained to a different component that actually loads" mean. I'm not sure what the desired change is for this issue

**Comment by AbhiramTadepalli** [comment]
Intended change: the course number / professor name should appear to load as long as the other data in the component is loading.

Why: so it looks uniform

_"chained to a different ~component~ **piece of data** that actually loads"_ means: the loading state of the course number / professor name should change when the loading state of a different piece of data in the same component changes.

**Comment by TyHil** [comment]
You can always just make it look like its loading until the rest of the data is ready. I kinda like the way it shows you what's loading tho. Maybe this could be a question for designers.
