### ISSUE TITLE
[Bug]: Some grade/RMP data never loads in the search results table

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#172]
### What did you expect to happen?

All possible grade and RMP data is loaded and displayed without extra user input

### What happened?

Grade and RMP data is sometimes loaded but not displayed. I.e. the skeleton wavy loaded never goes away.

This is because the component displaying this data does not realize the data it is displaying has changed status from `loading` to `done`. The component never realizes because it is technically displaying the same object of data, just some of the data in the object has changed. To fix this, every call to `setGrades` and `setRmp` must duplicate the object it takes in (`const newRmp = { ...rmp };
`) and edit/return that duplicated object (`newRmp`) instead of just editing the same object (`rmp`).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AndrewN20** [comment]
Which folder is that issue happening?

**Comment by TyHil** [comment]
I'm pretty sure it's only in `dashboard/index.tsx` where changes are needed

**Comment by AndrewN20** [comment]
Is this section is the one that I am supposed to modify?
![SectionToModify](https://github.com/user-attachments/assets/d821d394-ab35-41cb-b41a-c31078614729)
If so, I attempted to replace the code with const newRmp = { ...rmp };. But it seems to cause errors where the grades and ratings are not loading anymore.

**Comment by TyHil** [comment]
that is one of the places you should modify. In that section you'd replace lines 431-435 with the below. This moves the copy operation to the top so that in any condition a new object is always returned. Previously if they key was already in the object, the same object was returned, causing no update.
```
const newVal = {...old };
if (typeof newVal[key] !== 'undefined') {
  newVal[key] = value;
  return newVal;
}
```
kind of a difficult react-y concept to explain so lmk if that makes sense.

**Comment by AndrewN20** [comment]
I attempted to replace the "const newVal = {...old };" with "const newRpm = {...rpm };" and replace the "old" with "rpm" every instance. How do I check to see if there are any bugs or if my code has taken effect? Here below is the application running with my modification:
![TestResults1](https://github.com/user-attachments/assets/1002234c-5171-47a8-a5f7-72b4977350a5)

**Comment by AndrewN20** [comment]
Do some of the search results supposed to have missing rating and difficulty for some of the results, like GOVT 2305 Leslie Stanaland?

**Comment by TyHil** [comment]
Yeah some of them don't have data. They return an error and that's why the X shows up. But each of the data fetches is eventually a success or error, just some stay stuck on loading in the UI.

**Comment by TyHil** [comment]
It looks like the code here has not functionally changed, just the variable names have changed.

**Comment by AbhiramTadepalli** [comment]
Implemented Tyler's suggestion in https://github.com/UTDNebula/utd-trends/pull/234
