### ISSUE TITLE
[Bug]: Compare Component disappears

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#176]
### What happened?

Replication:
1. Search for CS2337
2. Add 2 results to compare
**2.5. Click on the compare tab**
4. **_Add_** GOVT2306 to the search
5. Compare Component disappears (tab remains)

### Cause
Probably has something to do with the Course Component disappearing when you tack on a different course to the search (this is intended behavior)

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rohancheruku** [comment]
same issue for any set of courses

**Comment by AbhiramTadepalli** [comment]
Added step 2.5: 

> **2.5. Click on the compare tab**

**Comment by AbhiramTadepalli** [comment]
https://github.com/UTDNebula/utd-trends/pull/188/commits/aa89093ded77bf8e11d0d161b909584114154de2 I just tested the above steps and was still encountering the compare component disappearing.
