### ISSUE TITLE
[Question]: Choose RMP for a professor with 2 profiles

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#178]
@TyHil how do you choose the correct RMP for a professor with 2 entries, like:
Dr. Octavious Smiley: https://www.ratemyprofessors.com/professor/2941177 & https://www.ratemyprofessors.com/professor/2982353
Dr. Scott Dollinger: https://www.ratemyprofessors.com/professor/2523207 & https://www.ratemyprofessors.com/professor/2651411

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TyHil** [comment]
I updated the new RMP scraper to address this. It chooses the prof with the larger number of ratings. Any value could be sorted on but I thought that was most appropriate.

**Comment by AbhiramTadepalli** [comment]
Sounds good

**Comment by AbhiramTadepalli** [comment]
Will be resolved when the PR gets merged
