### ISSUE TITLE
[Bug]: Most recent semester COURSE data (academic year 2024) not displaying

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#179]
### What did you expect to happen?

COURSE data should be up to date with the current academic year (2024)

### What happened?

[COURSE](https://nebula-labs.atlassian.net/wiki/spaces/TRENDS/pages/115507202/API+Documentation#Course) data (from the course API route) is only returning data up to academic year 2023

### Dependencies
- [ ] API team has to resolve issues scraping current academic year/F24 data from coursebook
- [ ] Verify newest data is being displayed in TRENDS for the Course Component

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiramTadepalli** [comment]
Find a course/prof that was taught for the first time in 2024/S24

**Comment by TyHil** [comment]
Resolved via API rerunning the Coursebook scraper
