### ISSUE TITLE
[Bug]: Ensure most recent semester's data is included in grade distributions

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#180]
### Overview
Verify that the most recent semester's data is being included in the grade distribution

- [ ] Find a professor that only taught in Spring24 or Summer24 semester
- [ ] See if their grade distribution included in search results for that course
- [ ] Ensure via console logs that the most recent semester is being included

https://github.com/UTDNebula/utd-trends/issues/179#issue-2498528820 - Could be related if there is an issue

### Version

Beta 0.1.0

### Relevant log output

```shell

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiramTadepalli** [comment]
Related to #179 and #181

**Comment by AbhiramTadepalli** [comment]
Find a course/prof that was taught for the first time in 2024/S24

**Comment by AbhiramTadepalli** [comment]
Aaron Smith's data is not present

**Comment by TyHil** [comment]
Resolved via an API fix
