### ISSUE TITLE
[Feature Request]: Default dashboard results sorting

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#184]
# Overview

Currently the default sorting is random. This is unintuitive.

# Proposal

A default sorting can be set up in the `generateCombosTable.ts`. This script maps searches to a list of unsorted search results. The last step in the script can be to sort all the results alphabetically.

**Comment by AbhiramTadepalli** [comment]
Annie wants to take this up

**Comment by AbhiramTadepalli** [comment]
@sparklingwter Is this issue about search autocomplete or search results?

**Comment by AbhiramTadepalli** [comment]
Team has decided to sort by alphabetical ascending
