### ISSUE TITLE
[Bug]: Professor Profile Picture not showing up

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#194]
### What did you expect to happen?

For professors with a profile picture, I expect it to show up in the Professor Overview component

### What happened?

For Zygmunt Haas (ie) his profile picture did not show up.

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiramTadepalli** [comment]
Testing shows that API is providing us with a dead link.

Richard Scotch shows up well, Zygmunt Haas does not.

**Comment by AbhiramTadepalli** [comment]
Check back on this. Josh needs to run the scraper again.

**Comment by TyHil** [comment]
The scraper was rerun and Zygmunt Haas is now showing up. Is this resolved?
