### ISSUE TITLE
[Feature Request] Change Avg_GPA column to Avg_Letter_Grades

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#196]
# Overview
On [09-10-2024](https://nebula-labs.atlassian.net/wiki/spaces/TRENDS/pages/245989406/2024-09-10+Meeting+notes) we decided to change the average GPA in the compare page to average letter grade
On [09-17-2024](https://nebula-labs.atlassian.net/wiki/spaces/TRENDS/pages/253394946/2024-09-17+Meeting+notes) we finalized on this design for the LHS: [LHS search-result-table Column Redesign](https://www.figma.com/design/OmGLQNdZBrgWGfamGjkci5/Redesign-Mockups)
This feature request focuses **only** on the average gpa/letter-grade column

# Proposal

- [x] Change the field to letters instead of numbers
- [x] Change the column header
- [x] Ensure sorting works (it should still sort based on average gpa)
- [x] Change filtering to show letter grades
- [x] Include a gradient background

## Supplementary Information
https://catalog.utdallas.edu/2024/graduate/policies/grades

**Comment by AbhiramTadepalli** [comment]
I recommend 2 people work on this

**Comment by sparklingwter** [comment]
Hi is it okay to assign this to me?

**Comment by AbhiramTadepalli** [comment]
yes

**Comment by TatvikReddy** [comment]
Can I be assigned to this, too?

**Comment by sparklingwter** [comment]
So @TyHil is going to join us and do the fourth checkbox :)

**Comment by TyHil** [comment]
@TatvikReddy I added you, what would everyone like to do?

**Comment by sparklingwter** [comment]
Tyler: change filter
Annie: change column header to "average grade", add the letter grade corresponding colors
Tatvik: change numbers to letters
