### ISSUE TITLE
[Feature Request] Add hover popup for Search Result Table

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#201]
# Overview

To show raw numbers when users hover on the letter grade and 5-star rating

# Proposal
- [ ] Hover on average Letter grade should show average GPA
- [ ] Hover on the rmp rating 5 stars should show rmp rating as a number

## Supplementary Information

Try to find a mui component that looks good for hovering

**Comment by George-Zhang5246** [comment]
Hover popups are done for the current design, not pushing for now since the design will change, and those changes aren't finalized yet.

**Comment by AbhiramTadepalli** [comment]
Blocked by #198 and #196

**Comment by TyHil** [comment]
@George-Zhang5246 no longer blocked!

**Comment by AbhiramTadepalli** [comment]
alr did it
