### ISSUE TITLE
[Feature Request] Add a dropdown multi-select filter for Semesters

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#208]
# Overview
Add a dropdown to select semesters to filter by
# Proposal

- [x] Add the dropdown component
- [x] Allow multi-select
- [x] Make sure relevant text appears in the dropdown when it's closed
- [x] Add a Select all option that also deselects all when clicked again
Play around with the idea to add an option to (a) select recent long-semesters (let's say 6 for now) and (b) To de/select summer semesters
## Supplementary Information
Here is the [figma mockup](https://www.figma.com/design/OmGLQNdZBrgWGfamGjkci5/Redesign-Mockups?node-id=0-1&node-type=canvas&t=XWDczVsj2H1Zuuoo-0) of it and [the meeting we finalized on an implementation](https://nebula-labs.atlassian.net/wiki/spaces/TRENDS/pages/261390342/09-24-2024+Meeting+notes).

**Comment by sparklingwter** [comment]
can I take this issue up since tyler and tatvik are alreadt resolving the main tasks for #196?

**Comment by TyHil** [comment]
@sparklingwter I assigned you

**Comment by TyHil** [comment]
The recent checkbox is not done but everything else is.

**Comment by TyHil** [comment]
Closing this as done, changes are covered in #249
