### ISSUE TITLE
[Feature Request] Add a "notification" indicating the number of results in the Compare tab

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#211]
# Overview

The "bubble notification" should be persistent.

This is a good way for users to see where the result they added to compare has gone

## Supplementary Information
![image](https://github.com/user-attachments/assets/2a4d5916-d2ba-4e67-81bf-fda42609bf4f)
from the [Figma](https://www.figma.com/design/OmGLQNdZBrgWGfamGjkci5/Redesign-Mockups?node-id=0-1&node-type=canvas&t=jfQQFef771aVynF4-0)

**Comment by TyHil** [comment]
@Shivhare-Ayush Looks like this is ready for a pull request!
