### ISSUE TITLE
[Feature Request] Hide Data Icon Button

### ISSUE THREAD

**Issue by eboysen** [UTDNebula/utd-trends#22]
# Overview

Describe the motivation behind your desired functionality.
Allow users to dynamically display data on the graphs without having to manually add and remove datasets from the expandable search grid

How would you like the user experience for this feature to work?
When the user hovers over the Autocomplete card at the top of the page, a MUI visibility icon should appear, if the user clicks it it should switch to the visibility off icon and the graphs should no longer display that dataset. 

# Proposal

Describe what changes need to be implemented to resolve this issue. Be as
detailed as possible so maintainers can best determine how to implement this
new feature.
A new state needs to be included at the app level to hold the invisible datasets. This will be used to store data outside of the dataset that is fed into our charts. Additionally, functionality needs to be added to move the datasets back and forth between these two states. 

## Supplementary Information

To give your feature more chance at being implemented, feel free to attach any
other documentation. For something highly-user facing, a UI mock-up or some
other form of wireframe is required.

**Comment by TyHil** [comment]
Hey @eboysen, ApexCharts currently lets us hide datasets in a single graph like below, less capable than what you've described but I was wondering if that would be adequate for this feature or if you wanted something more.
![Screen Recording - 7 April 2023_Trim (online-video-cutter com)](https://user-images.githubusercontent.com/63886162/230673224-cfd1ea4a-d478-462c-b871-b128987f147e.gif)
