### ISSUE TITLE
[Feature Request] Touch ups for Semester Filter

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#249]
# Overview

#240 added the Semester filter, but it's full functionality / UI is incomplete

# Proposal

Touch ups for Semester Filter
- [x] Make text font, size, & color consistent with the other filters
- [x] Each row in the dropdown is too tall relative to the other filters
- [x] Sort dropdown rows from most recent to least recent
- [x] Add Recent option
- [x] Dropdown rows should start under the filter, not on top of it
- [ ] #304
- [x] #305
- [x] #306
- [ ] #321

**Comment by sparklingwter** [comment]
hi, i thought this update was done for a bit with my update? if not, i can take still take care of it

**Comment by sparklingwter** [comment]
@AbhiramTadepalli please do not work on this because i will run out of issues if you do. Focus on your Mobile UI tyvm - ANNIE

**Comment by AbhiramTadepalli** [comment]
![image](https://github.com/user-attachments/assets/c4bfbcea-76a4-4a67-a8f2-53ee9d896b95)
Does this look too crowded?

**Comment by AbhiramTadepalli** [comment]
@TyHil can you help me get select all to have the bg color when it is fully checked?

**Comment by TyHil** [comment]
Looks like you might be able to manually apply the `.Mui-selected` class when the "select all" or "recent" checkboxes are checked

**Comment by AbhiramTadepalli** [comment]
- [ ] Add Tooltips to the 'Select All' and 'Recent' Filter options
- [ ] `academicSessions` do not match the semesters a professor taught a specific course

**Comment by AbhiramTadepalli** [comment]
In the latest commit https://github.com/UTDNebula/utd-trends/commit/3b60832450c5408472babe7d453d01437d3025fb I tried to center the text to the checkbox vertically but it didn't seem to work. Any ideas?

**Comment by TyHil** [comment]
The text is further embedded in a div and not centered in that, not sure what you can do
![image](https://github.com/user-attachments/assets/2342a5b5-7696-476d-8101-f34864b8e1a7)
