### ISSUE TITLE
[Internal] Reorganize components

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#250]
# Overview of Proposed Changes

The component folder organization is outdated

# Details

Currently the components are organized into 4 folders: common, graph, icons, and navigation. But there's 17 components in common and only 1-2 in each of the other folders. I'd propose a new organizational system with more/different folders. Not sure what these should be, that requires some discussion, but this change would be handy for developers.

**Comment by George-Zhang5246** [comment]
Maybe we could make 2 more folders, one for tables and one for info? There will still be a lot of components in the common folder though.

**Comment by TyHil** [comment]
@George-Zhang5246 I like that idea. To get more things out of common we can put anything table-related in the table folder too, like filters and rating.

I think we can combine the graph and icons folders too since those icons are only used in the graphs

**Comment by sparklingwter** [comment]
Hi, i was actually in the progress of combining the icon and the graph :) happy arranging!

**Comment by TyHil** [comment]
yay! @sparklingwter are you doing the arranging?

**Comment by sparklingwter** [comment]
maybe...

**Comment by TatvikReddy** [comment]
@TyHil do you think folders based on features would be a good system?
![image](https://github.com/user-attachments/assets/a0f79381-4d4b-4aea-862f-1c7228875096)

**Comment by TyHil** [comment]
@TatvikReddy yeah, that seems great!

**Comment by TyHil** [comment]
@TatvikReddy commit looks great if you want to make a PR!

**Comment by TatvikReddy** [comment]
Sorry @TyHil, I was about to combine the graph and icon stuff together. @sparklingwter told me about not doing that for the new graph we are going to add. So I will do a PR.

**Comment by TyHil** [comment]
No worries, sounds great!
