### ISSUE TITLE
[Feature Request] Autofocus SearchBar on homepage

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#253]
# Overview

I want to be able to immediately start typing when I open Trends.

# Proposal

Add a prop to the SearchBar to enable MUI `autoFocus` on the homepage, but not the dashboard.

**Comment by TyHil** [comment]
@NishilJ Can you try adding a comment like so to disable the eslint error
`// eslint-disable-next-line jsx-a11y/no-autofocus`

or you can disable the whole rule in the `package.json` file.

**Comment by TyHil** [comment]
After running `npm run format` this should be ready for a pull request!

**Comment by NishilJ** [comment]
what files would I commit after running that

**Comment by AbhiramTadepalli** [comment]
what did you change?
