### ISSUE TITLE
[Internal] Versioning + Release Notes

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#269]
# Overview of Changes

Would like to make the recent redesign start version 2.0.0
And release notes for similarly-grouped issues completed (not sprint-dependent)

@TyHil do you know how to do this?

**Comment by TyHil** [comment]
I haven't done that before but tutorials are abundant: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by AbhiramTadepalli** [comment]
That helped. Here is v2.0.0's release notes: https://github.com/UTDNebula/utd-trends/releases/tag/v2.0.0

Here is how it'll work:

```
vX.Y.Z

X updates for big features/functionality changes like the scheduling page, maybe ai stuff, a new home page

Y updates for feature drops / groups of features n things like that (rmp tags can be a Y++ version)

Z updates for fixes to previous Y versions
```

**Comment by AbhiramTadepalli** [comment]
That helped. Here is v2.0.0's release notes: https://github.com/UTDNebula/utd-trends/releases/tag/v2.0.0

Here is how it'll work:

```
vX.Y.Z

X updates for big features/functionality changes like the scheduling page, maybe ai stuff, a new home page

Y updates for feature drops / groups of features n things like that (rmp tags can be a Y++ version)

Z updates for fixes to previous Y versions
```
