### ISSUE TITLE
[Feature Request] Autocomplete for professors with middle name

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#272]
# Overview

If the professor has a middle name, like "Mehra Nouroz Borazjany", I cannot search for "Mehra Borazjany" in the searchbar because autocomplete doesn't recognize matches for "Mehra B"

# Proposal

Seperate first-and-middle name + lastname, so I can search for "Mehra Nou", "Mehra Bor", or "Mehra Nouroz B" to still have the autocomplete.

**Comment by AbhiramTadepalli** [comment]
@TyHil do you see any reason to not implement this?

**Comment by TyHil** [comment]
Duplicate of #260 I believe

**Comment by AbhiramTadepalli** [comment]
yep lol

**Comment by AbhiramTadepalli** [comment]
yep lol
