### ISSUE TITLE
[Feature Request] Selected Filter color

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#276]
# Overview
An additional visual indicator that a filter has been selected

# Proposal

When a filter has been selected, make the filter box have a darker shade / color

## Supplementary Information

Also, slight bug, after you select a filter, there is a purple outline around that one box until you click something else. Let's try to remove the outline after you close the filter.

**Comment by TyHil** [comment]
I believe the outline is for accessibility and should be kept. It indicates that you still have the input focused and can operate it with the keyboard.
