### ISSUE TITLE
[Feature Request] Rebuild home page

### ISSUE THREAD

**Issue by eboysen** [UTDNebula/utd-trends#28]
# Overview

The home page has gone through a redesign in hopes of increasing the readability and cohesiveness of the design language. There will be a couple of simple changes made to it most of which are some simple reformatting of the divs surrounding the search, logo and title. 

Recommend that you take a look at issue #27 as well if working on this feature branch.

Functionality will remain the same, only the html template and formatting need be adjusted.

# Proposal
The overlapping cards are being replaced with a single semi-transparent card, this should be a relatively simple fix. Simply edit the tsx file's return to adjust the html template so that it reflects the design better. Additionally, there are some spacing issues on mobile currently that should be adjusted at the same  time to reduce the margin and padding when on smaller screens.

Here is an screenshot from the design docs
![image](https://user-images.githubusercontent.com/50427509/159760225-2afc7b9d-f6ad-4918-9935-0f0fd301cf33.png)

**Comment by George-Zhang5246** [comment]
Maybe close this issue? I feel like the current homepage is better than the image.

**Comment by iamwood** [comment]
I agree. Once we get design and product people in to talk with us, I think we'll probably have redesign work all over, but we'll create a new issue for that once we get there.
