### ISSUE TITLE
[Internal] Move letter grade math to calculateGrades func

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#294]
# Overview of Proposed Changes

Instead of recalculating the letter grade based on the GPA in the `searchResultsTable` component, store this data like the gpa is stored in `calculateGrades`.

# Details

Changes are needed in and `searchResultsTable` the dashboard

Reference Skedge for an example:
https://github.com/UTDNebula/skedge/blob/bd999e5ea43893e600aef44f6110e62a0a79796c/src/pages/index.tsx#L86-L93

**Comment by AbhiramTadepalli** [comment]
Is what I did in https://github.com/UTDNebula/utd-trends/pull/301/commits/bc04095ed7563f53bb437e0b066b065cf67bcd5d fine?

**Comment by TyHil** [comment]
Yeah, that works!
