### ISSUE TITLE
[Bug]: Allow SPACE to select an autocomplete term without searching

### ISSUE THREAD

**Issue by AbhiramTadepalli** [UTDNebula/utd-trends#316]
### What did you expect to happen?

If I use the arrow keys to highlight an autocomplete result (after I've typed it out), I want SPACE to select it.

### What happened?

Clicking SPACE does not select the autocomplete I've highlighted. Instead:
(a) For 'CS 1200', if I highlight 'CS 1200.HON' and click SPACE, it selects 'CS 1200'

**Comment by AbhiramTadepalli** [comment]
Here's the deal: Pretty soon ENTER will initiate a new search. ENTER also selects the autocomplete term you have navigated to using arrow keys. I wanted a way to replace ENTER's functionality without causing a new search.
However, I realize that SPACE isn't the ideal thing to use because a person may have multiple names (first, middle, last).
TAB is an accessibility key, idt we should mess with that.

So @TyHil if you can't find a way to do this I'm fine closing the issue

**Comment by TyHil** [comment]
I suppose there could be a plus button on the right of each search result that would add it without doing a new search?

**Comment by AbhiramTadepalli** [comment]
I could try to make clicking not automatically search

But anything we can do from the keyboard?

**Comment by TyHil** [comment]
I can't think of anything from the keyboard

I feel like clicking and ENTER should have the same functionality tho

**Comment by AbhiramTadepalli** [comment]
Okay sure. That's how it will be once https://github.com/UTDNebula/utd-trends/pull/298 is merged in

**Comment by AbhiramTadepalli** [comment]
Okay sure. That's how it will be once https://github.com/UTDNebula/utd-trends/pull/298 is merged in
