### ISSUE TITLE
[Bug]: Spacing on top menu

### ISSUE THREAD

**Issue by eboysen** [UTDNebula/utd-trends#36]
### What did you expect to happen?

The spacing on the top menu should be uniform across displays, not dependent upon width.

### What happened?

The spacing is inconsistent across different screen sizes resulting in an inconsistent experience.
![image](https://user-images.githubusercontent.com/50427509/163430210-b5de8c8d-f09b-45a2-806f-8bc8ee5658fe.png)

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nathan-s-williams** [comment]
Fixed this bug while working on another issue. Please assign me as a co-owner so I may edit and push code for review.
