### ISSUE TITLE
[Feature Request] Display git SHA on page in preview/dev environments

### ISSUE THREAD

**Issue by Spaceface16518** [UTDNebula/utd-trends#43]
# Overview

I'm not sure if we're officially deploying with Vercel, but I know we're using it for preview builds. It would be cool to have the SHA of (and link to) the current deployed commit. Not only would this be aesthetically pleasing, it would also help discern what version of the website is currently being viewed.

# Proposal

Vercel provides the  `NEXT_PUBLIC_VERCEL_COMMIT_SHA` [environmental variable](https://vercel.com/docs/concepts/projects/environment-variables#preview-environment-variables) for deployments. It is then trivial to embed the SHA into builds using `process.env.NEXT_PUBLIC_VERCEL_COMMIT_SHA`. Given this data, it is also easy to link to the correct commit in the repo by embedding the hash into a github link.
```jsx
<a
  target="_blank"
  className="commit-link"
  href={'https://github.com/UTDNebula/utd-trends/commit/' + process.env.NEXT_PUBLIC_VERCEL_COMMIT_SHA}>
  {process.env.NEXT_PUBLIC_VERCEL_COMMIT_SHA.substring(0, 7)}
</a>
```

Depending on preference of the maintainers, this can be trivially skipped in production builds if we don't want to leak repo details. This can be configured two-fold, but checking `process.env.NODE_ENV` or `process.env.NEXT_PUBLIC_VERCEL_ENV` and by configuring vercel from the dashboard to not expose the `NEXT_PUBLIC_VERCEL_COMMIT_SHA` environmental variable for production builds.

## Supplementary Information

- https://vercel.com/docs/concepts/projects/environment-variables#preview-environment-variables
- https://github.com/vercel/community/discussions/56

**Comment by TyHil** [comment]
I think this will work, just need to get add `process.env.NEXT_PUBLIC_VERCEL_COMMIT_SHA` in Vercel: https://github.com/vercel/community/discussions/56

**Comment by TyHil** [comment]
@dlaunikitis you have the Vercel access right? Can you add the `VERCEL_GIT_COMMIT_SHA` to preview deployments (and if there's one for the git branch too that would be great) as such: https://github.com/orgs/vercel/discussions/56#discussioncomment-224509

**Comment by dlaunikitis** [comment]
Here is a link to all the available system environmental variables: https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables

I added `VERCEL_GIT_COMMIT_SHA` under the key `NEXT_PUBLIC_SHA` as asked. Let me know if you want anymore added :)
