### ISSUE TITLE
[Bug]:  Contribution.md Needs to be re-done

### ISSUE THREAD

**Issue by shoaibhuq** [UTDNebula/utd-trends#50]
### What did you expect to happen?

We are not a part of ACM anymore and there is a lot of documentation that still mentions/links them.

### What happened?

<img width="897" alt="image" src="https://user-images.githubusercontent.com/44373355/196307355-9e54a9a4-7c86-456c-8385-c21c7168a5f6.png">

^ Example of something that needs to be changed

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by George-Zhang5246** [comment]
Also change all Athena with UTD Trends
