### ISSUE TITLE
[Feature Request] Go to dashboard when something is searched.

### ISSUE THREAD

**Issue by George-Zhang5246** [UTDNebula/utd-trends#59]
# Overview

Describe the motivation behind your desired functionality.
The website should redirect to dashboard when an item is searched.

# Proposal

Describe what changes need to be implemented to resolve this issue. Be as
detailed as possible so maintainers can best determine how to implement this
new feature.

A redirect should be added to the function which executes when searched.
I tried importing and using redirect from react-router-dom and it didn’t work.

## Supplementary Information

To give your feature more chance at being implemented, feel free to attach any
other documentation. For something highly-user facing, a UI mock-up or some
other form of wireframe is required.

**Comment by TyHil** [comment]
Resolved with #17
