### ISSUE TITLE
[Bug]: Professor card highlighting

### ISSUE THREAD

**Issue by TyHil** [UTDNebula/utd-trends#71]
### What did you expect to happen?

The highlighting for "Average Difficulty" to be green when the number is lower and red when higher.
The highlighting for "Percentage Taking Again" to be green when the number is higher and red when lower.

### What happened?

The highlighting for "Average Difficulty" is reversed.
The highlighting for "Percentage Taking Again" is always red.

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by George-Zhang5246** [comment]
Fixed in consistency edits
